name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    name: Build / ubuntu-latest (x86_64) / ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Generate emblems
        run: target/release/cilki build-graphics

      - uses: actions/upload-artifact@v4
        with:
          name: cilki-assets
          path: emblems
